### ISSUE TITLE
exif error

### ISSUE THREAD

**Issue by trappedinspacetime** [becrux/wally#1]
Hi,
First of all, thank you for sharing your project. 
I am on Ubuntu 16.04 platform. I cloned `wally` and tried to build it. But I got the following error

         error: ‘class QSharedPointer<_ExifData>’ has no member named ‘get’
         exif_data_load_data(ed.get(), reinterpret_cast< const unsigned char * >(data.constData()), data.size());

I have the latest `libexif` library.
How can I fix it?

**Comment by trappedinspacetime** [comment]
I managed to build it. Current  QT version for Ubuntu 16.04 is `5.5.1` , wally uses recent version of it, so I built it via `QT 5.12.2`.
But when I run `./wally` in `build` directory nothing happens. 
There is no documentation about how to use it.

**Comment by becrux** [comment]
Hi,

It's still a porting to Qt5. The original project is here: http://www.becrux.com/index.php?page=projects&name=wally

I did this many years ago, but the code was too complicated and not mantainable anymore (as it always happens :-) ) ... so I decided to rewrite it from scratch.

I hope to have a running version soon.

**Comment by trappedinspacetime** [comment]
Thank you for responding. I am glad to hear that you will rebase the *Wally* from scratch. *Wally* is a useful and a popular application indeed. I hope it will revive soon.
It's good news from you.
All the best.
